### ISSUE TITLE
What version of melonloader is this working with?

### ISSUE THREAD

**Issue by ffffffffffffhhhhhhhhhhhh** [originalnicodr/CinematicUnityExplorer#25]
### Describe the issue

Are you using melonloader to get this running? I have yet to get it working on my system. If not could you clue me in on how you are getting this setup initially to actually load on a il2cpp game?

**Comment by originalnicodr** [comment]
Hey there! So sorry about the delay here, Github didnt properly notified me about it.

Would you mind explaining what game you were trying this with? And what problems did you have?

I havent tested melonloader that much. I would suggest instead to use [BepInEx](https://github.com/BepInEx/BepInEx/releases) instead since it works well with il2cpp games.

Having said that, I just merged a "fix" that should help with melonloader compatibility. Get the build you need from [here](https://github.com/originalnicodr/UnityExplorer/actions/runs/5913191327).

Let me know how it goes!

**Comment by originalnicodr** [comment]
Closing this as the user seems inactive.
